export const ROLE_PERMISSIONS_PAYLOAD = {
  sections: [
    {
      id: '0626b5bf-a61a-4236-b838-f56414aa56f2',
      key: 'products',
      sequence_number: 0,
      permissions: [
        {
          id: '1a77751f-6c16-4566-8bd0-953e3647f82e',
          parent_id: '',
          section_id: '',
          name: 'Поставщики',
          route: 'products/suppliers',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: '',
          sequence_number: 0,
          children: [
            {
              id: '57c8c603-218e-4512-a05e-95ed3f446b53',
              parent_id: '',
              name: 'Возможность редактирования поставщиков',
              route: 'products/suppliers/update/{:id}',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность редактирования поставщиков',
              is_active: false,
              slug: 'supplier-edit',
            },
            {
              id: '055648ec-fc43-4a88-8fdd-440bb252c72e',
              parent_id: '',
              name: 'Возможность просмотра списка поставщиков',
              route: 'products/suppliers',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность просмотра списка поставщиков',
              is_active: false,
              slug: 'supplier-list',
            },
            {
              id: 'e0aa19c3-a70b-4473-87a6-3832b4e41d21',
              parent_id: '',
              name: 'Возможность создания новых поставщиков',
              route: 'products/suppliers/create',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность создания новых поставщиков',
              is_active: false,
              slug: 'supplier-create',
            },
          ],
          is_active: false,
          slug: 'suppliers',
        },
        {
          id: 'ca32a386-b5f9-4e1c-b970-1f5cb1b9f51a',
          parent_id: '',
          section_id: '',
          name: 'Переоценка',
          route: 'products/revaluation',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: '',
          sequence_number: 0,
          children: [
            {
              id: '345e98b5-e8ce-4316-9572-e598d3a901ee',
              parent_id: '',
              name: 'Возможность одобрения переоценки',
              route: '/products/revaluation/view/{:id}',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность одобрения переоценки',
              is_active: false,
              slug: 'revaluation-accept',
            },
            {
              id: '0dfc88bd-3724-4e5b-9a95-7ed04c2374dd',
              parent_id: '',
              name: 'Возможность создания переоценки по курсу, марже и цене',
              route: 'products/revaluation/create/:id',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность создания переоценки по курсу, марже и цене',
              is_active: false,
              slug: 'revaluation-create',
            },
            {
              id: '26962e98-41cd-4a2f-b123-9c0cb962a5bb',
              parent_id: '',
              name: 'Возможность переоценки по файлу',
              route: 'products/revaluation/file',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность переоценки по файлу',
              is_active: false,
              slug: 'revaluation-file',
            },
            {
              id: '3080e176-3399-4749-a37e-1e5b89637d28',
              parent_id: '',
              name: 'Возможность просмотра процесса переоценок',
              route: 'products/revaluation',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность просмотра процесса переоценок',
              is_active: false,
              slug: 'product-revaluation',
            },
          ],
          is_active: false,
          slug: 'revaluation',
        },
        {
          id: '058ef03a-df68-4c4f-812b-0eda26cea577',
          parent_id: '',
          section_id: '',
          name: 'Каталог',
          route: 'products/catalog1',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description:
            'Тултип, объясняющий что делает cоздание товара, услуги, комплекта',
          sequence_number: 0,
          children: [
            {
              id: 'db7190af-390f-4822-94fe-40a528c1edaf',
              parent_id: '',
              name: 'Просмотр статистики каталога по товарам, услугам и комплектам',
              route: 'products/catalog?statistics=0',
              backend_route: '',
              http_method: 'ANY',
              description:
                'Возможность просматривать статистику по остаткам и себестоимости',
              is_active: false,
              slug: 'catalog-statistics',
            },
            {
              id: 'f27c7c8e-77b7-4df1-a10e-dd1a2ee4f6f5',
              parent_id: '',
              name: 'Создание товара, услуги, комплекта',
              route: 'products/create',
              backend_route: '',
              http_method: 'ANY',
              description:
                'Возможность создавать товары, услуги и комплекты, а также устанавливать на них цены и остатки',
              is_active: false,
              slug: 'product-create',
            },
            {
              id: 'ab3ad28e-8ef0-40a2-a9da-3c65c95e82c3',
              parent_id: '',
              name: 'Редактирование товара, услуги, комплекта',
              route: 'products/edit',
              backend_route: '',
              http_method: 'ANY',
              description:
                'Возможность менять описания и свойства товаров, услуг и комплектов',
              is_active: false,
              slug: 'product-edit',
            },
            {
              id: 'c9e3c56d-c942-44db-908b-2c15806da11e',
              parent_id: '',
              name: 'Просмотр и поиск товаров в каталоге',
              route: 'products/catalog',
              backend_route: '',
              http_method: 'ANY',
              description: 'Просмотр и поиск товаров в каталоге',
              is_active: false,
              slug: 'catalog-operations',
            },
            {
              id: 'a01e86a4-122a-41e4-b1fc-0c8007b0da00',
              parent_id: '',
              name: 'Возможность выгружать Каталог в Excel',
              route: 'v2/product-excel-export',
              backend_route: '',
              http_method: 'ANY',
              description: '',
              is_active: false,
              slug: 'product-excel-export',
            },
          ],
          is_active: false,
          slug: 'catalog',
        },
        {
          id: '5a71b9d0-9d97-46e9-8265-c0cfbf15a57e',
          parent_id: '',
          section_id: '',
          name: 'Справочник',
          route: 'products/handbook',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description:
            'Тултип, объясняющий что делает cоздание товара, услуги, комплекта',
          sequence_number: 0,
          children: [],
          is_active: false,
          slug: 'handbook',
        },
      ],
    },
    {
      id: 'e00c4747-5ccf-43ab-9433-588be3d00005',
      key: 'sales',
      sequence_number: 1,
      permissions: [
        {
          id: '94de2e86-e3c2-44f1-915c-8fab9a87a1a5',
          parent_id: '',
          section_id: '',
          name: 'Новая продажа',
          route: 'order/create',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: '',
          sequence_number: 0,
          children: [
            {
              id: '047ee2cc-5fcf-4a9d-b8f0-1f49d9bd297c',
              parent_id: '',
              name: 'Возможность делать ручные скидки на чек и товар',
              route: 'new-sale/discount',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность делать ручные скидки на чек и товар',
              is_active: false,
              slug: 'manual-discount',
            },
            {
              id: '83ef1b26-281c-4beb-9176-0d5b962068f5',
              parent_id: '',
              name: 'Возможность делать транзакции продаж',
              route: 'order/create',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность делать транзакции продаж',
              is_active: false,
              slug: 'order-new',
            },
            {
              id: 'ebd024af-3aa7-49d3-a407-8060b3285973',
              parent_id: '',
              name: 'Просмотр продаж всех продавцов',
              route: 'order/all-sales',
              backend_route: '',
              http_method: 'ANY',
              description:
                'Когда роль включена, в модуле “Все продажи” отображаются продажи всех продавцов. При отключенной роли видны только собственные продажи',
              is_active: false,
              slug: 'show-all-sales',
            },
          ],
          is_active: false,
          slug: 'new-sale',
        },
        {
          id: '77792139-fa18-4ff0-98ef-9e35ada59daa',
          parent_id: '',
          section_id: '',
          name: 'Все продажи',
          route: 'order/all',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: '',
          sequence_number: 0,
          children: [
            {
              id: '425386cf-d51d-4fcf-b217-d62e0f085f1f',
              parent_id: '',
              name: 'Возможность просмотра списка транзакций за весь период',
              route: 'order/bro',
              backend_route: '',
              http_method: 'ANY',
              description:
                'Возможность просмотра списка транзакций за весь период',
              is_active: false,
              slug: 'orders',
            },
          ],
          is_active: false,
          slug: 'all-sales',
        },
      ],
    },
    {
      id: 'c2267912-bcbf-4a1b-a572-753dd242bb3c',
      key: 'clients',
      sequence_number: 2,
      permissions: [
        {
          id: 'a734891d-272f-47fe-a9d4-2168c4eef268',
          parent_id: '',
          section_id: '',
          name: 'Все клиенты',
          route: 'clients',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: '',
          sequence_number: 0,
          children: [
            {
              id: 'a3d208da-5898-497c-820a-7a652d2afc53',
              parent_id: '',
              name: 'Возможность просмотра списка клиентов',
              route: 'clients',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность просмотра списка клиентов',
              is_active: false,
              slug: 'clients',
            },
          ],
          is_active: false,
          slug: 'all-clients',
        },
      ],
    },
    {
      id: 'a154ad91-7fbf-4413-ac7e-bf4de005444b',
      key: 'marketing',
      sequence_number: 3,
      permissions: [
        {
          id: '8f35218c-9a9e-48b3-be04-391e6fe1bc7d',
          parent_id: '',
          section_id: '',
          name: 'Акции',
          route: 'promos',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: 'Акции',
          sequence_number: 0,
          children: [
            {
              id: 'f1b996fb-5cae-4528-8a2f-532799d579f3',
              parent_id: '',
              name: ' Просмотр страницы',
              route: 'marketing/promotions',
              backend_route: '',
              http_method: 'ANY',
              description: ' Просмотр страницы',
              is_active: false,
              slug: 'promo',
            },
          ],
          is_active: false,
          slug: 'promos',
        },
      ],
    },
    {
      id: '4519bd93-fdbc-428f-8010-6da882f0fd84',
      key: 'reports',
      sequence_number: 4,
      permissions: [
        {
          id: '0ba88835-ec69-4d3e-9fd9-7aa0c824719f',
          parent_id: '',
          section_id: '',
          name: 'Магазин',
          route: 'reports/shop',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: 'Магазин',
          sequence_number: 0,
          children: [
            {
              id: 'b80ef171-4dca-4185-a27c-0cf520405096',
              parent_id: '',
              name: 'Сводный отчет',
              route: '**-reports/shop',
              backend_route: '',
              http_method: 'ANY',
              description: 'Сводный отчет',
              is_active: false,
              slug: 'summary-report',
            },
          ],
          is_active: false,
          slug: 'reports-shop',
        },
      ],
    },
    {
      id: 'a64023cc-f96e-4d95-abb3-f5fd8fca01c0',
      key: 'finance',
      sequence_number: 5,
      permissions: [
        {
          id: '4b60e335-dc6b-405a-be77-56a317e90490',
          parent_id: '',
          section_id: '',
          name: 'Состояние счетов',
          route: 'finance/state',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: 'Состояние счетов',
          sequence_number: 0,
          children: [
            {
              id: '1c18164c-2c9c-41a5-aa93-80b92bb229db',
              parent_id: '',
              name: 'Возможность просмотра состояния счетов',
              route: 'finance/state',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность просмотра состояния счетов',
              is_active: false,
              slug: 'state-view',
            },
          ],
          is_active: false,
          slug: 'finance-state',
        },
      ],
    },
    {
      id: 'a27b7379-31e8-4574-82a1-3be4cdb00d81',
      key: 'settings',
      sequence_number: 6,
      permissions: [
        {
          id: 'c687338d-f0e4-4309-bd88-db9dfa4ab0f1',
          parent_id: '',
          section_id: '',
          name: 'Профиль',
          route: 'settings/profile',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: '',
          sequence_number: 0,
          children: [
            {
              id: '0aacb736-9b34-4676-a3ba-2d476a434dc3',
              parent_id: '',
              name: 'Возможность редактирования профиля',
              route: 'settings/profile',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность редактирования профиля',
              is_active: false,
              slug: 'settings-profile',
            },
          ],
          is_active: false,
          slug: 'settings-profiles',
        },
        {
          id: 'ae8659f5-7b92-4c0d-a889-f2a356165bb1',
          parent_id: '',
          section_id: '',
          name: 'Компания',
          route: 'settings/company',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: '',
          sequence_number: 0,
          children: [
            {
              id: 'cf22a739-abab-4a9c-afbe-f5f367a9c877',
              parent_id: '',
              name: 'Возможность редактирования настроек Компании',
              route: 'settings/company',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность редактирования настроек Компании',
              is_active: false,
              slug: 'company-edit',
            },
          ],
          is_active: false,
          slug: 'settings-company',
        },
      ],
    },
    {
      id: '19b01a2d-e91e-4e45-bb74-b832405d8cab',
      key: 'management',
      sequence_number: 7,
      permissions: [
        {
          id: 'f1678fb3-ecbe-49a6-950f-6cfb86756472',
          parent_id: '',
          section_id: '',
          name: 'Сотрудники',
          route: 'management/employees',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: 'Management',
          sequence_number: 0,
          children: [
            {
              id: 'e6955a19-f0e2-462f-8e93-eb61e4dd4b9e',
              parent_id: '',
              name: 'Возможность создания новых сотрудников',
              route: 'management/employees/create',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность создания новых сотрудников',
              is_active: false,
              slug: 'employee-create',
            },
            {
              id: '29f71763-fe3f-4af5-b4d2-73c98531cd58',
              parent_id: '',
              name: 'Возможность удаления сотрудников',
              route: 'management/employees/delete/:id',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность удаления сотрудников',
              is_active: false,
              slug: 'employee-delete',
            },
            {
              id: '434dcea4-574c-4f0f-932f-474c9a5983a9',
              parent_id: '',
              name: 'Возможность редактирования сотрудника',
              route: 'user/{id}',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность редактирования сотрудника',
              is_active: false,
              slug: 'employee-edit',
            },
            {
              id: 'dd85ad8a-7fe5-401d-a990-1b5e576eec08',
              parent_id: '',
              name: 'Возможность просмотра списка сотрудников',
              route: 'management/employees',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность просмотра списка сотрудников',
              is_active: false,
              slug: 'employee-list',
            },
          ],
          is_active: false,
          slug: 'employees',
        },
        {
          id: '2127a4a0-eda5-4ec0-b736-ee2eb255873f',
          parent_id: '',
          section_id: '',
          name: 'Роли',
          route: 'management/roles',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: '',
          sequence_number: 0,
          children: [
            {
              id: 'b4ab0d5c-e9bc-4f60-9cf3-f9ce771e612d',
              parent_id: '',
              name: 'Возможность просмотра списка ролей',
              route: 'management/roles',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность просмотра списка ролей',
              is_active: false,
              slug: 'role-list',
            },
            {
              id: 'b2b25861-0cfe-420c-893f-78eaac9db29b',
              parent_id: '',
              name: 'Возможность удаления роли ',
              route: 'management/roles/delete',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность удаления роли ',
              is_active: false,
              slug: 'management-role-delete',
            },
            {
              id: '0597c8c4-e31d-4a91-982f-bfbc9897b16c',
              parent_id: '',
              name: 'Возможность редактирования роли',
              route: 'management/roles/:id',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность редактирования роли',
              is_active: false,
              slug: 'role-edit',
            },
            {
              id: '1721db3c-ad09-4303-a0c1-06b7fb8a6fad',
              parent_id: '',
              name: 'Возможность создания новой роли',
              route: 'management/roles/create',
              backend_route: '',
              http_method: 'ANY',
              description: 'Возможность создания новой роли',
              is_active: false,
              slug: 'role-create',
            },
          ],
          is_active: false,
          slug: 'roles',
        },
      ],
    },
    {
      id: '028b7298-cf0e-4714-9141-c3025a6d42a2',
      key: 'dashboard',
      sequence_number: 8,
      permissions: [
        {
          id: 'fc3f810f-8cdd-4429-927b-70f934791664',
          parent_id: '',
          section_id: '',
          name: 'Просмотр дашборда по продажам магазина',
          route: 'dashboard/access',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description:
            'Просмотр дашборда по продажам магазина, к которому привязан',
          sequence_number: 0,
          children: [],
          is_active: false,
          slug: 'dashboard-orders',
        },
        {
          id: '0581c1bd-2925-4014-bb63-dabc7ae81b8f',
          parent_id: '',
          section_id: '',
          name: 'Возможность создания и управления таргетами',
          route: 'dashboard/target',
          backend_route: '',
          http_method: 'ANY',
          hide_from_ui: false,
          description: 'Возможность создания и управления таргетами',
          sequence_number: 0,
          children: [],
          is_active: false,
          slug: 'target',
        },
      ],
    },
  ],
  user_id: '',
} as const;

export const ROLE_PERMISSION_SECTIONS = ROLE_PERMISSIONS_PAYLOAD.sections;

export type RolePermissionSection =
  (typeof ROLE_PERMISSIONS_PAYLOAD.sections)[number];
