ALTER TABLE "Product"
ALTER COLUMN "quantity" TYPE DOUBLE PRECISION
USING "quantity"::DOUBLE PRECISION;

ALTER TABLE "ProductStock"
ALTER COLUMN "quantity" TYPE DOUBLE PRECISION
USING "quantity"::DOUBLE PRECISION;

ALTER TABLE "SaleItem"
ALTER COLUMN "quantity" TYPE DOUBLE PRECISION
USING "quantity"::DOUBLE PRECISION;
